name: Monitoramento SECOM

on:
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora (0 minutos de cada hora)

jobs:
  monitor:
    runs-on: windows-latest  # Usa Windows para compatibilidade

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Ajuste para 3.13 se preferir

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar monitoramento
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: python monitor.py

      - name: Upload logs (opcional)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: monitoring-logs
          path: output.log